name: Tests
on: push

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install tools
        run: |
          python -m pip install --upgrade pip pytest
          pip install coverage
      
      - name: Install requests
        run: python -m pip install requests
        
      - name: Install pandas
        run: python -m pip install pandas
      
      - name: Install sql
        run: python -m pip install sqlalchemy
      
      - name: Install matplotlib
        run: python -m pip install matplotlib
        
      - name: Test with unittest
        run: |
          python3 -m unittest testcrypto.py

      - name: Check code coverage                        #new from here down
        run: |
          python3 -m coverage run -m unittest testcrypto.py
          python3 -m coverage report
          python3 -m coverage html
          
      - name: Archive code coverage HTML report
        uses: actions/upload-artifact@v2
        with:
           name: code-coverage-report
           path: htmlcov